# NUMPY ARRAYS

In [1]:
ht = [150, 120, 130, 180, 140]

In [4]:
ht_m = [x/100 for x in ht]
ht_m

[1.5, 1.2, 1.3, 1.8, 1.4]

In [34]:
wt = [56, 60, 70, 50, 45]
w = wt.copy()

In [5]:
bmi = wt/ht^2

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [9]:
ht_wt = list(zip(ht_m, wt))
ht_wt

[(1.5, 56), (1.2, 60), (1.3, 70), (1.8, 50), (1.4, 45)]

In [13]:
ht_wt[0][1]/(ht_wt[0][0]**2)

24.88888888888889

In [14]:
[x[1]/x[0]**2 for x in ht_wt]

[24.88888888888889,
 41.66666666666667,
 41.42011834319526,
 15.432098765432098,
 22.95918367346939]

In [15]:
[x[1]/x[0]**2 for x in zip(ht_m, wt)]

[24.88888888888889,
 41.66666666666667,
 41.42011834319526,
 15.432098765432098,
 22.95918367346939]

In [16]:
import numpy

In [17]:
type(numpy)

module

In [ ]:
numpy.#press a tab

In [18]:
import numpy as np

In [ ]:
np.#press a tab

In [19]:
from numpy import array

In [20]:
array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate()

In [21]:
ht_m

[1.5, 1.2, 1.3, 1.8, 1.4]

In [23]:
ht_m=np.array(ht_m)

In [24]:
wt = np.array(wt)

In [26]:
ht_m

array([1.5, 1.2, 1.3, 1.8, 1.4])

In [27]:
wt

array([56, 60, 70, 50, 45])

In [30]:
bmi = wt/ht_m**2
bmi

array([24.88888889, 41.66666667, 41.42011834, 15.43209877, 22.95918367])

In [31]:
bmi.ndim

1

In [32]:
bmi.shape

(5,)

In [33]:
bmi.size

5

In [36]:
arr = np.array([[10,20], [30, 50], [60,70]])
arr

array([[10, 20],
       [30, 50],
       [60, 70]])

In [37]:
arr.ndim

2

In [38]:
arr.shape

(3, 2)

In [39]:
arr.size

6